<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>cf278c9b-afaa-4434-ba27-3ffe5d3b8fff</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\FieldValidators\**" />
    <Content Remove="Data\FieldValidators\**" />
    <EmbeddedResource Remove="Data\FieldValidators\**" />
    <None Remove="Data\FieldValidators\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Data\CommonFieldValidatorFunctions.cs" />
    <Compile Remove="Data\CommonRegularExpressionValidationPatterns.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Components\Pages\AboutMe\TermsOfService.razor" />
    <Content Remove="Components\Pages\PopupModal.razor" />
    <Content Remove="wwwroot\bootstrap\js\FoodLogging.css" />
    <Content Remove="wwwroot\customcsspages\FoodLogging.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\bootstrap\css\FoodLogging.css" />
    <None Include="wwwroot\customcsspages\FoodLogging.css" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\bootstrap\NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" Version="1.10.5" />
    <PackageReference Include="BootstrapBlazor" Version="7.11.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Plotly.NET" Version="4.2.0" />
    <PackageReference Include="Plotly.NET.CSharp" Version="0.11.0" />
    <PackageReference Include="Syncfusion.Blazor.Charts" Version="21.2.10" />
    <PackageReference Include="Syncfusion.Blazor.DataVizCommon" Version="21.2.10" />
  </ItemGroup>

</Project>
