// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteFirstDraft.Data.Models;

#nullable disable

namespace WebsiteFirstDraft.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119081328_CreateWeightLogsTable")]
    partial class CreateWeightLogsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.CalorieLogs", b =>
                {
                    b.Property<int>("CalorieLog_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalorieLog_Id"));

                    b.Property<int?>("Calories_Burned")
                        .HasColumnType("int");

                    b.Property<int?>("Calories_Consumed")
                        .HasColumnType("int");

                    b.Property<DateTime>("Log_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Net_Calories")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("CalorieLog_Id");

                    b.ToTable("Calorie_Logs");
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.ExerciseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesBurnedPerMinute")
                        .HasColumnType("float")
                        .HasColumnName("calories_burnt_per_minute");

                    b.Property<string>("ExerciseNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exercise_name");

                    b.Property<string>("ExerciseTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exercise_type");

                    b.Property<string>("IntensityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intensity");

                    b.HasKey("Id");

                    b.ToTable("exercise_types", (string)null);
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.FoodType", b =>
                {
                    b.Property<int>("Food_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Food_Id"));

                    b.Property<double>("Calories_Per_Gram")
                        .HasColumnType("float");

                    b.Property<double>("Carbs_Per_Gram")
                        .HasColumnType("float");

                    b.Property<double>("Fat_Per_Gram")
                        .HasColumnType("float");

                    b.Property<string>("Food_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Food_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Protein_Per_Gram")
                        .HasColumnType("float");

                    b.HasKey("Food_Id");

                    b.ToTable("Food_items");
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"));

                    b.Property<int>("Body_Weight")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Daily_Calories")
                        .HasColumnType("int");

                    b.Property<int>("Daily_Calories_Burnt_Through_Exercise")
                        .HasColumnType("int");

                    b.Property<int>("Daily_Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Daily_Cardio")
                        .HasColumnType("int");

                    b.Property<int>("Daily_Fat")
                        .HasColumnType("int");

                    b.Property<int>("Daily_Flexibility")
                        .HasColumnType("int");

                    b.Property<int>("Daily_Protein")
                        .HasColumnType("int");

                    b.Property<int>("Daily_Strength")
                        .HasColumnType("int");

                    b.Property<double>("Daily_Weight_Change")
                        .HasColumnType("float");

                    b.Property<bool>("Dyslexia_Friendly_Font")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("High_Contrast_Mode")
                        .HasColumnType("bit");

                    b.Property<bool>("Larger_Font_Size")
                        .HasColumnType("bit");

                    b.Property<int>("Login_Streak")
                        .HasColumnType("int");

                    b.Property<int>("Maintenance_Calories")
                        .HasColumnType("int");

                    b.Property<bool>("Minimal_Interface")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Progress_Data")
                        .HasColumnType("bit");

                    b.Property<bool>("Reduced_Animations")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_Calories")
                        .HasColumnType("int");

                    b.Property<string>("Tracking_Preferences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visual_Rewards")
                        .HasColumnType("bit");

                    b.Property<int>("Weekly_Calories")
                        .HasColumnType("int");

                    b.Property<int>("Weekly_Calories_Burnt_Through_Exercise")
                        .HasColumnType("int");

                    b.Property<int>("Weekly_Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Weekly_Fat")
                        .HasColumnType("int");

                    b.Property<int>("Weekly_Protein")
                        .HasColumnType("int");

                    b.Property<double>("Weekly_Weight_Change")
                        .HasColumnType("float");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.UserExercises", b =>
                {
                    b.Property<int>("UserExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("users_exercise_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserExerciseId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("users_exercises");
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.UserFoodItems", b =>
                {
                    b.Property<int>("UsersFoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("users_food_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsersFoodItemId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added");

                    b.Property<int>("FoodId")
                        .HasColumnType("int")
                        .HasColumnName("food_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UsersFoodItemId");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("users_food_items", (string)null);
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.WeightLog", b =>
                {
                    b.Property<int>("WeightLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeightLogId"));

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("WeightLogId");

                    b.HasIndex("UserId");

                    b.ToTable("Weight_Logs");
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.UserExercises", b =>
                {
                    b.HasOne("WebsiteFirstDraft.Data.DatabaseTableModels.ExerciseType", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteFirstDraft.Data.DatabaseTableModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.UserFoodItems", b =>
                {
                    b.HasOne("WebsiteFirstDraft.Data.DatabaseTableModels.FoodType", "FoodType")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteFirstDraft.Data.DatabaseTableModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteFirstDraft.Data.DatabaseTableModels.WeightLog", b =>
                {
                    b.HasOne("WebsiteFirstDraft.Data.DatabaseTableModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
